//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

[RequireComponent (typeof (Rigidbody))]

public class ProjectileTrajectory : MonoBehaviour
{
	// Constants
	public float projectileRange = 500.0f;
	public float currentVelocity = 0.0f; 

	// Class Members
	GameObject explosion;
	float distance;
	Vector3 spawnLocation;

	void Start() {
		spawnLocation = transform.position;
	}
	
	void FixedUpdate() {
		rigidbody.AddForce(transform.TransformDirection(Vector3.forward) * 100.0f);
	}
	
	void Update() {
		distance = Vector3.Distance(spawnLocation, transform.position);
		
		if(distance > projectileRange) {
			Destroy(gameObject);
		}
	}
	
	void OnEnable() {
		StartCoroutine(Shoot());
	}
	
	void OnDisable() {
		StopAllCoroutines();
	}
	
	IEnumerator Shoot()
	{
		float travelledDistance = 0;
		while (travelledDistance < projectileRange)
		{
			travelledDistance  += currentVelocity * Time.deltaTime;
			transform.position += transform.forward * (currentVelocity * Time.deltaTime);
			yield return 0;
		}
		this.Recycle();
	}
	
	void OnCollisionEnter(Collision collision) {
		// Local Variables
		ContactPoint contact = collision.contacts[0];
		//GameObject thisExplosion = (GameObject)GameObject.Instantiate(explosion, contact.point + (contact.normal * 5.0f), Quaternion.identity);
		
		if(collision.gameObject.tag == "enemy") {
			Destroy(collision.gameObject);
		}
		
		//Destroy(thisExplosion, 2.0f);
		Destroy(gameObject);
	}
}
